### ISSUE TITLE
Have to hit Rebuild when restarting Home Assistant

### ISSUE THREAD

**Issue by Sawtaytoes** [richardhopton/smartbed-mqtt#48]
Every time I install a Home Assistant update that requires a restart, I have to click "Rebuild" on this add-on. I'm using Tempur-Pedic, and if I don't click "Rebuild", I lose access to entities like the under-bed light.

<img width="674" alt="image" src="https://github.com/user-attachments/assets/25df2541-ef6e-41fa-b910-1afdaae440b0">

**Comment by mljenkinsdotcom** [comment]
I have noticed any time I restart HA, I have to restart this add on.  If I do not restart, my entities are all unavailable.  Have you tried a restart instead of rebuild?  I personally think the issue is this add on may be starting before the MQTT add on, but I haven't had any time to track it down since a restart usually fixes it.

**Comment by richardhopton** [comment]
Interestingly the add-on configuration states it needs MQTT so HA should orchestrate the startup of each. I think it's likely more likely that MQTT has started but HA isn't listening to the MQTT yet when this add-on sends the messages.

**Comment by mm98** [comment]
I noticed the same. I disabled `Start on boot` on `smartbed-mqtt` and instead added an automation, which stops and starts `smartbed-mqtt` when HA starts with a 10 sec delay. This ensures that `smartbed-mqtt` is started __after__ `Mosquitto broker` (MQTT) is initialized.

```yaml
alias: "Home Assistant: Started"
description: ""
triggers:
  - event: start
    trigger: homeassistant
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - action: hassio.addon_stop
    metadata: {}
    data:
      addon: xxxxxxxxx_smartbed-mqtt
  - action: hassio.addon_start
    metadata: {}
    data:
      addon: xxxxxxxxx_smartbed-mqtt
mode: single

```

**Comment by Sawtaytoes** [comment]
Here's what I ended up doing because SmartMQTT can sometimes stop randomly as well as mess up during boot:

```yaml
alias: Reset Master Bedroom Bed Light
description: >-
  The Smartbed MQTT add-on gets messed up at startup and sometimes during
  operation. Because of this, we need to restart the add-on when these events
  occur.
triggers:
  - trigger: homeassistant
    event: start
  - trigger: state
    entity_id:
      - light.master_bedroom_bed_safety_lights
    to: unavailable
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - if:
      - condition: state
        entity_id: binary_sensor.smartbed_mqtt_running
        state: "on"
    then:
      - action: hassio.addon_restart
        metadata: {}
        data:
          addon: 3f6f8ac8_smartbed-mqtt
    else:
      - action: hassio.addon_start
        metadata: {}
        data:
          addon: 3f6f8ac8_smartbed-mqtt
    alias: Start if stopped or restart if running
mode: single
```

Change `light.master_bedroom_bed_safety_lights` to match yours. Not sure if the addon name is different for each person.

You can find out if the service is running using the Home Assistant Supervisor:

![Image](https://github.com/user-attachments/assets/194021c4-e40c-4720-a53e-dc1ee66b8924)

Search for "Running" and Enable it for SmartMQTT. In my case, it enabled for all addons:

![Image](https://github.com/user-attachments/assets/94423d7d-1cbf-4121-8314-df3f571b4abe)
